AMF =
{
  INSTANCE_ID = 0 ;            # 0 is the default
  PID_DIRECTORY = "/var/run";   # /var/run is the default

  AMF_NAME = "OAI-AMF";

  RELATIVE_CAPACITY = 30;
  # Display statistics about whole system (in seconds)
  STATISTICS_TIMER_INTERVAL = 20;

  CORE_CONFIGURATION:
  {
    EMERGENCY_SUPPORT = "false";
  };

  GUAMI:
  {
    MCC = "208"; MNC = "95"; RegionID = "128"; AMFSetID = "1"; AMFPointer = "1"
  }

  SERVED_GUAMI_LIST = (
    {MCC = "208"; MNC = "95"; RegionID = "128"; AMFSetID = "1"; AMFPointer = "0"}
  );

  PLMN_SUPPORT_LIST = ({
    MCC = "208"; MNC = "95"; TAC = 33456;
    SLICE_SUPPORT_LIST = (
      {SST = 1; SD = "000001"}
      ,{SST = 2; SD = "000002"}
      ,{SST = 3; SD = "000003"}
      ,{SST = 4; SD = "000004"}
     )
  });

  INTERFACES:
  {
    NGAP_AMF:
    {
      INTERFACE_NAME = "eth1";
      IPV4_ADDRESS   = "read";
      PORT           = 38412;
      PPID           = 60;
    };

    SBI:
    {
      INTERFACE_NAME = "eth0";
      IPV4_ADDRESS   = "read";
      PORT           = 80;
      API_VERSION    = "v1";
      HTTP2_PORT     = 8080;

      SMF_INSTANCES_POOL = (
        {SMF_INSTANCE_ID = 1; IPV4_ADDRESS = "0.0.0.0"; PORT = "80"; HTTP2_PORT = 8080, VERSION = "v1"; FQDN = "localhost", SELECTED = ""}
      );
    };

    NRF :
    {
      IPV4_ADDRESS = "192.168.70.101";
      PORT         = 80;            # Default: 80
      API_VERSION  = "v1";
      FQDN         = "localhost"
    };

    AUSF :
    {
      IPV4_ADDRESS = "192.168.70.135";
      PORT         = 80;            # Default: 80
      API_VERSION  = "v1";
      FQDN         = "ausf.oai-5gcn.eur"
    };

    UDM :
    {
      IPV4_ADDRESS = "192.168.70.134";
      PORT         = 80;    # Default: 80
      API_VERSION  = "v1";
      FQDN         = "localhost"
    };

    NSSF :
    {
      IPV4_ADDRESS = "192.168.70.132";
      PORT         = 80;            # Default: 80
      API_VERSION  = "v1";
      FQDN         = "nssf.oai-5gcn.eur"
    };

  };

  SUPPORT_FEATURES:
  {
     NF_REGISTRATION = "no";  # Set to yes if AMF resgisters to an NRF
     NRF_SELECTION   = "yes";    # Set to yes to enable NRF discovery and selection
     EXTERNAL_NRF    = "no";     # Set to yes if AMF works with an external NRF
     SMF_SELECTION   = "yes";    # Set to yes to enable SMF discovery and selection
     EXTERNAL_AUSF   = "yes";    # Set to yes if AMF works with an external AUSF
     EXTERNAL_UDM    = "yes";     # Set to yes if AMF works with an external UDM
     EXTERNAL_NSSF   = "yes";    # Set to yes if AMF works with an external NSSF
     USE_FQDN_DNS    = "no";   # Set to yes if AMF relies on a DNS to resolve NRF/SMF/UDM/AUSF's FQDN
     USE_HTTP2       = "no";        # Set to yes to enable HTTP2 for AMF server
  }

  AUTHENTICATION:
  {
    MYSQL_server = "mysql"; # MySQL Server address
    MYSQL_user   = "test";   # Database server login
    MYSQL_pass   = "test";   # Database server password
    MYSQL_db     = "oai_db";     # Your database name
    RANDOM = "true";
  };

  NAS:
  {
    ORDERED_SUPPORTED_INTEGRITY_ALGORITHM_LIST = ["NIA1" , "NIA2"] ;
    ORDERED_SUPPORTED_CIPHERING_ALGORITHM_LIST = ["NEA1" , "NEA2"] ;
  };
};

MODULES =
{
  NGAP_MESSAGE = (
    {MSG_NAME = "NGSetupRequest"; ProcedureCode = 21; TypeOfMessage = "initialMessage"}
  );
};
